### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: count >= 0 required but it was -1

### ISSUE THREAD

**Issue by koufesser** [kusumotolab/NIL#66]
I am using JDK corretto-11.0.23 and I couldn`t start the project because of this error.
Here is example on examples folder. Could you give me a hint am i doing something wrong?
> java -Xmx12G -jar ./build/libs/NIL-all.jar -s /home/koufesser/NIL/src/test/resources/examples/
```
14:37:50.819 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Start
14:37:51.218 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - 6 code blocks have been extracted.
14:37:51.223 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 1: Index creation has been completed.
14:37:51.233 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 1: Clone detection has been completed.
14:37:51.233 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 2: Index creation has been completed.
14:37:51.234 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 2: Clone detection has been completed.
14:37:51.234 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 3: Index creation has been completed.
14:37:51.236 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 3: Clone detection has been completed.
14:37:51.236 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 4: Index creation has been completed.
14:37:51.237 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 4: Clone detection has been completed.
14:37:51.238 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 5: Index creation has been completed.
14:37:51.239 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 5: Clone detection has been completed.
14:37:51.239 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 6: Index creation has been completed.
14:37:51.240 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 6: Clone detection has been completed.
14:37:51.240 [main] INFO jp.ac.osaka_u.sdl.nil.NILMain - Partition 7: Index creation has been completed.
Exception in thread "main" java.lang.IllegalArgumentException: count >= 0 required but it was -1
	at io.reactivex.rxjava3.core.Flowable.range(Flowable.java:4396)
	at jp.ac.osaka_u.sdl.nil.NILMain.run(NILMain.kt:58)
	at jp.ac.osaka_u.sdl.nil.NILMainKt.main(NILMain.kt:77)

```
Also, i had a problem with building a jar:
>./gradlew ShadowJar
.... 
```
Compilation with Kotlin compile daemon was not successful
java.rmi.ServerError: Error occurred in server thread; nested exception is: 
        java.lang.IllegalAccessError: class org.jetbrains.kotlin.com.intellij.util.io.FileChannelUtil (in unnamed module @0x1572270e) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x1572270e
```

I solved it by adding this line to gradle properties
   `org.gradle.jvmargs=-Xmx1000m`
that increases maximum memory allocation pool
Maybe that can be mentioned in readme

**Comment by T45K** [comment]
the 1st one, which is `IllegalArgumentException` during execution, is caused by partition size.
NIL partitions extracted code blocks in clone detection phase to limit memory usage.
this way, the above exception occurs when partition size is bigger than the number of extracted code blocks.
NIL provides `-p` option to specify partition size.
i'm sure that appending `-p 1` to command will solve the issue.

the 2nd one, your error message seems Kotlin daemon issue.
i guess suppressing Kotlin daemon by `-Pkotlin.incremental=false` command option will solve the issue.

thank you

**Comment by koufesser** [comment]
thank you, it worked!
